import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { apiClient } from "../client"
import { USE_MOCKS } from "@/lib/feature-flags"
import type { AiMessageMetadata } from "@/lib/signalr"

/**
 * Type of conversation.
 * - `Direct`: One-on-one chat.
 * - `Group`: Group chat (e.g. project chat).
 */
export type ConversationType = "Direct" | "Group"
type ConversationTypeRaw = ConversationType | number | string | null | undefined

/**
 * Represents a participant in a conversation.
 */
export type ConversationParticipant = {
  /** Unique identifier of the user */
  userId: string
  /** Full name of the user */
  fullName: string
  /** URL to the user's avatar image */
  avatarUrl: string | null
  /** Timestamp when the user last read the conversation */
  lastReadAt?: string | null
  /** Timestamp when the user joined the conversation */
  joinedAt?: string | null
  /** Timestamp of the user's last login */
  lastLogin?: string | null
  /** Whether the user has muted the conversation */
  isMuted?: boolean
}

/**
 * Represents a chat conversation.
 */
export type Conversation = {
  /** Unique identifier of the conversation */
  id: string
  /** Type of the conversation */
  type: ConversationType
  /** Title of the conversation (null for direct chats) */
  title: string | null
  /** Timestamp of the last message in the conversation */
  lastMessageAt: string | null
  /** Short, single-line preview of the most recent message (decrypted + truncated) */
  lastMessagePreview: string | null
  /** Sender id of the most recent message */
  lastMessageSenderId: string | null
  /** Full name of the last message sender */
  lastMessageSenderName: string | null
  /** Whether the last message was generated by AI */
  lastMessageIsAi: boolean
  /** List of participants in the conversation */
  participants: ConversationParticipant[]
  /** Number of unread messages for the current user */
  unreadCount: number
}

type ConversationFromApi = Omit<
  Conversation,
  "type" | "lastMessagePreview" | "lastMessageSenderId" | "lastMessageSenderName" | "lastMessageIsAi"
> & {
  type: ConversationTypeRaw
  lastMessagePreview?: string | null
  lastMessageSenderId?: string | null
  lastMessageSenderName?: string | null
  lastMessageIsAi?: boolean | null
}

/**
 * Information about the sender of a message.
 */
export type SenderInfo = {
  /** Unique identifier of the sender */
  id: string
  /** Full name of the sender */
  fullName: string
  /** URL to the sender's avatar image */
  avatarUrl: string | null
}

/**
 * Information about the message being replied to.
 */
export type ReplyToInfo = {
  /** Unique identifier of the replied message */
  id: string
  /** Content of the replied message */
  content: string
  /** Full name of the sender of the replied message */
  fullName: string
}

export type MessageReactionSummary = {
  emoji: string
  count: number
  userIds: string[]
}

/**
 * Represents a chat message.
 */
export type ChatMessage = {
  /** Unique identifier of the message */
  id: string
  /** ID of the conversation this message belongs to */
  conversationId?: string
  /** Content of the message */
  content: string
  /** ID of the sender */
  senderId?: string
  /** Information about the sender */
  sender?: SenderInfo | null
  /** Full name of the sender (denormalized) */
  senderFullName?: string
  /** Avatar URL of the sender (denormalized) */
  senderAvatarUrl?: string | null
  /** ID of the message being replied to */
  replyToId?: string | null
  /** Information about the message being replied to */
  replyTo?: ReplyToInfo | null
  /** Timestamp when the message was created */
  createdAt: string
  /** Timestamp when the message was last updated */
  updatedAt?: string | null
  /** Whether the message has been deleted */
  isDeleted?: boolean
  /** Whether the message has been edited */
  isEdited?: boolean
  /** Whether the message was generated by AI assistant */
  isAiGenerated?: boolean
  aiMetadata?: AiMessageMetadata | null
  isPinned?: boolean
  pinnedAt?: string | null
  pinnedByUserId?: string | null
  reactions?: MessageReactionSummary[]
}

/**
 * Metadata for pagination.
 */
export type PaginationMeta = {
  /** Current page number */
  page: number
  /** Number of items per page */
  pageSize: number
  /** Total number of items */
  total: number
  /** Total number of pages */
  totalPages: number
  /** Whether there is a next page */
  hasNext: boolean
  /** Whether there is a previous page */
  hasPrevious: boolean
}

/**
 * Detailed information about a conversation participant.
 */
export type ConversationParticipantDetails = ConversationParticipant & {
  /** Unique identifier of the user */
  userId: string
}

const normalizeConversationType = (value: ConversationTypeRaw): ConversationType => {
  if (value === "Direct" || value === 0 || value === "0" || `${value}`.toLowerCase() === "direct") {
    return "Direct"
  }
  return "Group"
}

const normalizeMessage = (message: ChatMessage): ChatMessage => {
  const senderId = message.senderId ?? message.sender?.id
  return {
    ...message,
    senderId,
    senderFullName: message.senderFullName ?? message.sender?.fullName,
    senderAvatarUrl: message.senderAvatarUrl ?? message.sender?.avatarUrl ?? null,
    replyToId: message.replyToId ?? message.replyTo?.id ?? null,
    reactions: message.reactions ?? [],
    isPinned: message.isPinned ?? false,
    pinnedAt: message.pinnedAt ?? null,
    pinnedByUserId: message.pinnedByUserId ?? null,
  }
}

/**
 * Hook to fetch the list of conversations for the current user.
 * @returns Query result containing the list of conversations.
 */
export function useConversations() {
  return useQuery({
    queryKey: ["chat", "conversations"],
    queryFn: async () => {
      if (USE_MOCKS) {
        return []
      }
      const response = await apiClient.get<ConversationFromApi[]>("/chat/conversations")
      return response.data.map((conv) => ({
        ...conv,
        type: normalizeConversationType(conv.type),
        lastMessagePreview: conv.lastMessagePreview ?? null,
        lastMessageSenderId: conv.lastMessageSenderId ?? null,
        lastMessageSenderName: conv.lastMessageSenderName ?? null,
        lastMessageIsAi: conv.lastMessageIsAi ?? false,
      }))
    },
    // F-07: no polling — list is kept fresh via SignalR invalidateQueries
  })
}

/**
 * Hook to fetch messages for a specific conversation.
 * @param conversationId - The ID of the conversation.
 * @param page - The page number to fetch (default: 1).
 * @param pageSize - The number of messages per page (default: 50).
 * @returns Query result containing the messages and pagination metadata.
 */
export function useMessages(conversationId: string, page = 1, pageSize = 50) {
  return useQuery({
    queryKey: ["chat", "messages", conversationId, page, pageSize],
    queryFn: async () => {
      if (USE_MOCKS) {
        return { data: [], pagination: null }
      }
      type BackendResponse = {
        data: ChatMessage[]
        pagination: PaginationMeta
      }
      const response = await apiClient.get<BackendResponse>(
        `/chat/conversations/${conversationId}/messages`,
        {
          params: { page, pageSize },
        }
      )
      return {
        data: response.data.data.map((item) => normalizeMessage({ ...item, conversationId })),
        pagination: response.data.pagination,
      }
    },
    enabled: Boolean(conversationId),
    staleTime: 0, // Always refetch when returning to chat (SignalR sends live messages that need to be persisted)
    refetchOnMount: "always", // Ensure fresh data when component mounts
  })
}

/**
 * Hook to fetch participants of a specific conversation.
 * @param conversationId - The ID of the conversation.
 * @returns Query result containing the list of participants.
 */
export function useParticipants(conversationId: string | null) {
  return useQuery({
    queryKey: ["chat", "participants", conversationId],
    queryFn: async () => {
      if (USE_MOCKS) return []
      type ParticipantResponse = ConversationParticipantDetails[]
      const response = await apiClient.get<ParticipantResponse>(
        `/chat/conversations/${conversationId}/participants`
      )
      return response.data
    },
    enabled: Boolean(conversationId),
    staleTime: 30_000,
  })
}

/**
 * Hook to send a message to a conversation.
 * @returns Mutation result for sending a message.
 */
export function useSendMessage() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async ({
      conversationId,
      content,
      replyToId,
      isAiGenerated,
    }: {
      conversationId: string
      content: string
      replyToId?: string | null
      isAiGenerated?: boolean
    }) => {
      if (USE_MOCKS) {
        return { messageId: "mock-id" }
      }
      type BackendResponse = {
        messageId: string
        createdAt: string
      }
      const response = await apiClient.post<BackendResponse>(
        `/chat/conversations/${conversationId}/messages`,
        {
          content,
          replyToId: replyToId || null,
          isAiGenerated: isAiGenerated || false,
        }
      )
      return { messageId: response.data.messageId, createdAt: response.data.createdAt }
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["chat", "messages", variables.conversationId] })
      queryClient.invalidateQueries({ queryKey: ["chat", "conversations"] })
    },
  })
}

export function useEditMessage() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async ({ messageId, content }: { messageId: string; content: string }) => {
      const response = await apiClient.put<{ messageId: string }>(`/chat/messages/${messageId}`, {
        content,
      })
      return response.data
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["chat", "messages"] })
      queryClient.invalidateQueries({ queryKey: ["chat", "conversations"] })
    },
  })
}

export function useDeleteMessage() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async (messageId: string) => {
      await apiClient.delete(`/chat/messages/${messageId}`)
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["chat", "messages"] })
      queryClient.invalidateQueries({ queryKey: ["chat", "conversations"] })
    },
  })
}

export function useToggleMessageReaction() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async ({ messageId, emoji }: { messageId: string; emoji: string }) => {
      const response = await apiClient.post(`/chat/messages/${messageId}/reactions`, { emoji })
      return response.data
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["chat", "messages"] })
    },
  })
}

export function useSetMessagePin() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: async ({ messageId, isPinned }: { messageId: string; isPinned: boolean }) => {
      const response = await apiClient.put(`/chat/messages/${messageId}/pin`, { isPinned })
      return response.data
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["chat", "messages"] })
    },
  })
}

/**
 * Hook to create a new direct conversation with another user.
 * @returns Mutation result for creating a direct conversation.
 */
function useCreateConversation(endpointFn: (id: string) => string) {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: async (id: string) => {
      if (USE_MOCKS) return { conversationId: "mock-id" }
      const response = await apiClient.post<{ conversationId: string }>(endpointFn(id))
      return { conversationId: response.data.conversationId }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["chat", "conversations"] })
    },
  })
}

export function useCreateDirectConversation() {
  return useCreateConversation((id) => `/chat/conversations/direct/${id}`)
}

export function useCreateProjectConversation() {
  return useCreateConversation((id) => `/chat/conversations/project/${id}`)
}
