using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace DevHunt.CoreApi.Services.Chat;

/// <summary>
/// DTO for sending a message.
/// </summary>
public class SendMessageDto
{
    /// <summary>
    /// Message content.
    /// </summary>
    [Required]
    [MaxLength(10000)]
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// ID of the message to reply to (optional).
    /// </summary>
    public Guid? ReplyToId { get; set; }

    /// <summary>
    /// Indicates if this message was generated by AI assistant.
    /// When true, the message is marked as AI-generated for tracking and UI purposes.
    /// </summary>
    public bool IsAiGenerated { get; set; }

    /// <summary>
    /// Server-side AI transparency summary. Not bindable from public JSON.
    /// </summary>
    [JsonIgnore]
    public string? AiMetadataJson { get; set; }

    /// <summary>
    /// Server-side full AI transparency payload. Not bindable from public JSON.
    /// </summary>
    [JsonIgnore]
    public string? AiDetailsJson { get; set; }
}

/// <summary>
/// DTO for editing a message.
/// </summary>
public class EditMessageDto
{
    /// <summary>
    /// New message content.
    /// </summary>
    [Required]
    [MaxLength(10000)]
    public string Content { get; set; } = string.Empty;
}

/// <summary>
/// DTO for toggling an emoji reaction on a message.
/// </summary>
public class MessageReactionDto
{
    /// <summary>Unicode emoji to add or remove (max 32 chars).</summary>
    [Required]
    [MaxLength(32)]
    public string Emoji { get; set; } = string.Empty;
}

/// <summary>
/// DTO for pinning or unpinning a message.
/// </summary>
public class PinMessageDto
{
    /// <summary>When true, pins the message and records who pinned it; false clears pin metadata.</summary>
    public bool IsPinned { get; set; }
}

/// <summary>
/// DTO for creating a group chat.
/// </summary>
public class CreateGroupChatDto
{
    /// <summary>
    /// Group chat title.
    /// </summary>
    [Required]
    [MaxLength(255)]
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// List of participant IDs to invite.
    /// </summary>
    [Required]
    public List<Guid> ParticipantIds { get; set; } = new();
}

/// <summary>
/// DTO for managing chat mute status.
/// </summary>
public class MuteDto
{
    /// <summary>
    /// Whether the chat is muted.
    /// </summary>
    [Required]
    public bool Muted { get; set; }
}

/// <summary>
/// Typed service outcome wrapping payload, HTTP-style status code, and error text. Used across
/// chat and channel services instead of throwing for expected validation failures.
/// </summary>
public class ChatResult<T>
{
    /// <summary>True when <see cref="Data"/> is populated and no error occurred.</summary>
    public bool IsSuccess { get; set; }
    /// <summary>Payload on success; null on failure.</summary>
    public T? Data { get; set; }
    /// <summary>Human-readable failure reason when <see cref="IsSuccess"/> is false.</summary>
    public string? ErrorMessage { get; set; }
    /// <summary>Suggested HTTP status for controllers mapping this result.</summary>
    public int StatusCode { get; set; }

    /// <summary>Constructs a 200 success result with data.</summary>
    /// <param name="data">Payload returned to the caller.</param>
    /// <returns>Successful result instance.</returns>
    public static ChatResult<T> Success(T data) => new() { IsSuccess = true, Data = data, StatusCode = 200 };
    /// <summary>Constructs a failed result with message and status code.</summary>
    /// <param name="message">Error text for clients or logs.</param>
    /// <param name="statusCode">HTTP status to propagate.</param>
    /// <returns>Failed result instance with no data.</returns>
    public static ChatResult<T> Failure(string message, int statusCode) => new() { IsSuccess = false, ErrorMessage = message, StatusCode = statusCode };
}

/// <summary>Non-generic <see cref="ChatResult{T}"/> for operations with no response body.</summary>
public class ChatResult
{
    /// <summary>True when the operation completed without error.</summary>
    public bool IsSuccess { get; set; }
    /// <summary>Human-readable failure reason when <see cref="IsSuccess"/> is false.</summary>
    public string? ErrorMessage { get; set; }
    /// <summary>Suggested HTTP status for controllers mapping this result.</summary>
    public int StatusCode { get; set; }

    /// <summary>Constructs a 200 success result with no payload.</summary>
    /// <returns>Successful result instance.</returns>
    public static ChatResult Success() => new() { IsSuccess = true, StatusCode = 200 };
    /// <summary>Constructs a failed result with message and status code.</summary>
    /// <param name="message">Error text for clients or logs.</param>
    /// <param name="statusCode">HTTP status to propagate.</param>
    /// <returns>Failed result instance.</returns>
    public static ChatResult Failure(string message, int statusCode) => new() { IsSuccess = false, ErrorMessage = message, StatusCode = statusCode };
}

/// <summary>
/// Concrete payload returned by <see cref="IChatService.SendMessageAsync"/>.
/// Strongly typed so callers (e.g. LLM streaming) don't have to reflect over
/// an anonymous object to pull the saved message id back out.
/// </summary>
public sealed record MessageSendResult(Guid MessageId, DateTime CreatedAt);
