using System;
using System.ComponentModel.DataAnnotations;

namespace DevHunt.Infrastructure.Models;

/// <summary>
/// Persisted AI-generated knowledge artifact for a project ("Project Passport").
/// Each artifact represents one section of the project's knowledge base,
/// providing ongoing context to the AI assistant beyond the initial planning phase.
/// </summary>
public class ProjectArtifact
{
    public Guid Id { get; set; }

    [Required]
    public Guid ProjectId { get; set; }

    /// <summary>
    /// Artifact section type: overview, tech_stack, architecture, roadmap, decisions
    /// </summary>
    [Required, MaxLength(50)]
    public string Type { get; set; } = "overview";

    /// <summary>
    /// Display title for the section.
    /// </summary>
    [MaxLength(200)]
    public string? Title { get; set; }

    /// <summary>
    /// The artifact content — markdown-formatted text generated by AI.
    /// </summary>
    [Required]
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Monotonically increasing version number for this artifact type within a project.
    /// </summary>
    public int Version { get; set; } = 1;

    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// User who triggered the generation (null for auto-generated on plan apply).
    /// </summary>
    public Guid? GeneratedByUserId { get; set; }
}
