// <auto-generated />
using System;
using DevHunt.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevHunt.Infrastructure.Migrations
{
    [DbContext(typeof(DevHuntDbContext))]
    [Migration("20251102010048_ShowcaseProjectsImplementation")]
    partial class ShowcaseProjectsImplementation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevHunt.Infrastructure.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.ConversationParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "UserId")
                        .IsUnique();

                    b.ToTable("Conversation_Participants");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InviteeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InviterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("InviteeId");

                    b.HasIndex("InviterId");

                    b.HasIndex("ProjectId", "InviteeId")
                        .IsUnique()
                        .HasDatabaseName("IX_Invitation_Project_Invitee");

                    b.ToTable("Invitations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1645aa-0ad9-4d51-919e-8b332afbbb5f"),
                            CreatedAt = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            InviteeId = new Guid("f8f32d7a-0a82-4a81-90f5-6a55f4e5f8d9"),
                            InviterId = new Guid("39fa21f7-02ad-4941-9dff-64ec7b441d72"),
                            Message = "Need help with architecture choices and feature vetting.",
                            ProjectId = new Guid("d7d17e84-7a92-4c2f-bc67-bc0612548723"),
                            Role = "mentor",
                            Status = "pending"
                        });
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReplyToId");

                    b.HasIndex("SenderId");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("IX_Messages_Conversation_CreatedAt");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("IX_Messages_Project_CreatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.ModerationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReporterId");

                    b.HasIndex("UserId");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("ModerationReports");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExpectedDurationDays")
                        .HasColumnType("integer");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxTeamSize")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.PrimitiveCollection<string[]>("RequiredRoles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("ShowcasePublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<string[]>("TechStack")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f01de92-32e5-459d-bd48-3c968ccb67f1"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Platform that helps hackathon organizers manage teams and tasks in real time.",
                            Featured = false,
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            RequiredRoles = new string[0],
                            ShowcasePublished = false,
                            Status = "active",
                            TechStack = new[] { "ASP.NET Core", "React", "PostgreSQL" },
                            Title = "Hackathon Companion",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Visibility = "public"
                        },
                        new
                        {
                            Id = new Guid("d7d17e84-7a92-4c2f-bc67-bc0612548723"),
                            CreatedAt = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Showcase service for AI projects with ratings, feedback, and GitHub integration.",
                            Featured = false,
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            RequiredRoles = new string[0],
                            ShowcasePublished = false,
                            Status = "planning",
                            TechStack = new[] { "Next.js", "Node.js", "Redis" },
                            Title = "AI Showcase Hub",
                            UpdatedAt = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Visibility = "public"
                        });
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.ProjectRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FilledCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredSkillsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "RoleName");

                    b.ToTable("Project_Roles");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.ProjectTechStack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ProficiencyRequired")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("ProjectId", "SkillId")
                        .IsUnique();

                    b.ToTable("Project_Tech_Stack");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ReviewedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedUserId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("ProjectId", "ReviewerId", "ReviewedUserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.ShowcaseProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DemoUrl")
                        .HasColumnType("text");

                    b.Property<string>("DemoVideoUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<int>("LikesCount")
                        .HasColumnType("integer");

                    b.Property<string>("MetricsJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("text");

                    b.Property<string>("ScreenshotsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("Featured", "PublishedAt");

                    b.ToTable("Showcase_Projects");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text")
                        .HasColumnName("IconUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("ActualHours")
                        .HasColumnType("real");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<float?>("EstimatedHours")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4f5025e-6ebf-4c0a-bf9f-6b9e1d6da98d"),
                            AssignedToUserId = new Guid("56d8f0bd-16ce-4880-a94b-0c81273790d2"),
                            CreatedAt = new DateTime(2025, 11, 2, 1, 0, 47, 865, DateTimeKind.Utc).AddTicks(2324),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Deadline = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Priority = "medium",
                            ProjectId = new Guid("7f01de92-32e5-459d-bd48-3c968ccb67f1"),
                            Status = "in_progress",
                            Title = "Set up CI/CD"
                        },
                        new
                        {
                            Id = new Guid("fd8f047c-d31e-469d-85ed-7f608d3f6306"),
                            AssignedToUserId = new Guid("39fa21f7-02ad-4941-9dff-64ec7b441d72"),
                            CreatedAt = new DateTime(2025, 11, 2, 1, 0, 47, 865, DateTimeKind.Utc).AddTicks(3942),
                            CreatedByUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Priority = "medium",
                            ProjectId = new Guid("d7d17e84-7a92-4c2f-bc67-bc0612548723"),
                            Status = "todo",
                            Title = "Collect early adopter feedback"
                        });
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contribution")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("ContributionScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02efec63-0182-4a60-9088-f13faf9d3651"),
                            Contribution = "Built the backend and frontend MVP in 72 hours.",
                            IsLeader = false,
                            JoinedAt = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("7f01de92-32e5-459d-bd48-3c968ccb67f1"),
                            Role = "fullstack",
                            Status = "active",
                            UserId = new Guid("56d8f0bd-16ce-4880-a94b-0c81273790d2")
                        },
                        new
                        {
                            Id = new Guid("29d08d5d-f8c3-4df8-8638-524c2f46d9a6"),
                            Contribution = "Mentored the team and reviewed architecture decisions.",
                            IsLeader = false,
                            JoinedAt = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectId = new Guid("7f01de92-32e5-459d-bd48-3c968ccb67f1"),
                            Role = "mentor",
                            Status = "active",
                            UserId = new Guid("f8f32d7a-0a82-4a81-90f5-6a55f4e5f8d9")
                        });
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Experience")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Github")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Linkedin")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Timezone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f8f32d7a-0a82-4a81-90f5-6a55f4e5f8d9"),
                            Bio = "Helps teams with solution architecture and code reviews.",
                            CreatedAt = new DateTime(2025, 11, 2, 1, 0, 47, 863, DateTimeKind.Utc).AddTicks(8288),
                            Email = "mentor@devhunt.io",
                            FullName = "Maria Kotova",
                            IsActive = true,
                            IsVerified = false,
                            PasswordHash = "DEMO_PASSWORD_HASH",
                            Role = "mentor",
                            Skills = new string[0],
                            Timezone = "UTC+3"
                        },
                        new
                        {
                            Id = new Guid("56d8f0bd-16ce-4880-a94b-0c81273790d2"),
                            Bio = "Full-stack developer working with React and .NET.",
                            CreatedAt = new DateTime(2025, 11, 2, 1, 0, 47, 864, DateTimeKind.Utc).AddTicks(224),
                            Email = "builder@devhunt.io",
                            FullName = "Ivan Goncharov",
                            IsActive = true,
                            IsVerified = false,
                            PasswordHash = "DEMO_PASSWORD_HASH",
                            Role = "participant",
                            Skills = new string[0],
                            Timezone = "UTC+4"
                        },
                        new
                        {
                            Id = new Guid("39fa21f7-02ad-4941-9dff-64ec7b441d72"),
                            Bio = "Product manager with 6 years of experience.",
                            CreatedAt = new DateTime(2025, 11, 2, 1, 0, 47, 864, DateTimeKind.Utc).AddTicks(228),
                            Email = "product@devhunt.io",
                            FullName = "Daria Nikolaeva",
                            IsActive = true,
                            IsVerified = false,
                            PasswordHash = "DEMO_PASSWORD_HASH",
                            Role = "pm",
                            Skills = new string[0],
                            Timezone = "UTC+1"
                        });
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.UserSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId")
                        .IsUnique();

                    b.ToTable("User_Skills");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.ConversationParticipant", b =>
                {
                    b.HasOne("DevHunt.Infrastructure.Models.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHunt.Infrastructure.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.Invitation", b =>
                {
                    b.HasOne("DevHunt.Infrastructure.Models.User", "Invitee")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("InviteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHunt.Infrastructure.Models.User", "Inviter")
                        .WithMany("SentInvitations")
                        .HasForeignKey("InviterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevHunt.Infrastructure.Models.Project", "Project")
                        .WithMany("Invitations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitee");

                    b.Navigation("Inviter");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.Message", b =>
                {
                    b.HasOne("DevHunt.Infrastructure.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevHunt.Infrastructure.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevHunt.Infrastructure.Models.Message", "ReplyTo")
                        .WithMany()
                        .HasForeignKey("ReplyToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevHunt.Infrastructure.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Project");

                    b.Navigation("ReplyTo");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.ModerationReport", b =>
                {
                    b.HasOne("DevHunt.Infrastructure.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevHunt.Infrastructure.Models.User", null)
                        .WithMany("Reports")
                        .HasForeignKey("UserId");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.ProjectRole", b =>
                {
                    b.HasOne("DevHunt.Infrastructure.Models.Project", "Project")
                        .WithMany("ProjectRoles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.ProjectTechStack", b =>
                {
                    b.HasOne("DevHunt.Infrastructure.Models.Project", "Project")
                        .WithMany("TechStacks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHunt.Infrastructure.Models.Skill", "Skill")
                        .WithMany("ProjectTechStacks")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.Review", b =>
                {
                    b.HasOne("DevHunt.Infrastructure.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHunt.Infrastructure.Models.User", "ReviewedUser")
                        .WithMany()
                        .HasForeignKey("ReviewedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DevHunt.Infrastructure.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ReviewedUser");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.ShowcaseProject", b =>
                {
                    b.HasOne("DevHunt.Infrastructure.Models.Project", "Project")
                        .WithMany("ShowcaseProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.TaskItem", b =>
                {
                    b.HasOne("DevHunt.Infrastructure.Models.User", "AssignedToUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevHunt.Infrastructure.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.TeamMember", b =>
                {
                    b.HasOne("DevHunt.Infrastructure.Models.Project", "Project")
                        .WithMany("TeamMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHunt.Infrastructure.Models.User", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.UserSkill", b =>
                {
                    b.HasOne("DevHunt.Infrastructure.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevHunt.Infrastructure.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.Project", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("ProjectRoles");

                    b.Navigation("ShowcaseProjects");

                    b.Navigation("Tasks");

                    b.Navigation("TeamMembers");

                    b.Navigation("TechStacks");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.Skill", b =>
                {
                    b.Navigation("ProjectTechStacks");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("DevHunt.Infrastructure.Models.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("Reports");

                    b.Navigation("SentInvitations");

                    b.Navigation("TeamMemberships");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}

