// <auto-generated />
using System;
using DevHunt.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DevHunt.Infrastructure.Migrations
{
    [DbContext(typeof(DevHuntDbContext))]
    [Migration("20260310180000_AddCodeAnalysisEmbeddings")]
    partial class AddCodeAnalysisEmbeddings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Raw SQL migration — no EF model changes.
            // Full model snapshot is maintained in DevHuntDbContextModelSnapshot.cs
        }
    }
}
