// <auto-generated />
using System;
using DevHunt.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DevHunt.Infrastructure.Migrations
{
    [DbContext(typeof(DevHuntDbContext))]
    [Migration("20260317120000_AddTotpTwoFactorAuth")]
    partial class AddTotpTwoFactorAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Column additions only — full model snapshot in DevHuntDbContextModelSnapshot.cs
        }
    }
}
