using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DevHunt.Infrastructure.Models;

/// <summary>
/// Message in a direct conversation or project group chat.
/// Supports reply-to (message reply), editing, and soft-delete.
/// Corresponds to ERD: Messages (devhunt_erd.puml, lines 136-148).
/// </summary>
[Table("Messages")]
public class Message
{
    /// <summary>
    /// Unique identifier of the message.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Message sender identifier.
    /// </summary>
    public Guid SenderId { get; set; }

    /// <summary>
    /// Message text.
    /// </summary>
    [Required]
    [MaxLength(10000)]
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Message type: direct (personal), group (group), or project (in project).
    /// </summary>
    public MessageType MessageType { get; set; }

    /// <summary>
    /// Conversation identifier (for direct and group).
    /// </summary>
    public Guid? ConversationId { get; set; }

    /// <summary>
    /// Project identifier (for project messages).
    /// </summary>
    public Guid? ProjectId { get; set; }

    /// <summary>
    /// Identifier of the message being replied to (reply-to).
    /// </summary>
    public Guid? ReplyToId { get; set; }

    /// <summary>
    /// Message send date and time.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Message edited flag.
    /// </summary>
    public bool IsEdited { get; set; }

    /// <summary>
    /// Message deleted flag (soft-delete).
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// Indicates if this message was generated by AI assistant.
    /// Used for tracking AI usage and special rendering in UI.
    /// </summary>
    public bool IsAiGenerated { get; set; }

    /// <summary>
    /// Compact, durable AI transparency summary for generated messages.
    /// Heavy details live in <see cref="AiDetails"/> and are pruned by TTL.
    /// </summary>
    public string? AiMetadataJson { get; set; }

    /// <summary>
    /// Whether this message is pinned in its conversation.
    /// </summary>
    public bool IsPinned { get; set; }

    /// <summary>
    /// When this message was pinned.
    /// </summary>
    public DateTime? PinnedAt { get; set; }

    /// <summary>
    /// User who pinned this message.
    /// </summary>
    public Guid? PinnedByUserId { get; set; }

    // Navigation properties

    /// <summary>
    /// Message sender.
    /// </summary>
    [ForeignKey(nameof(SenderId))]
    public User Sender { get; set; } = null!;

    /// <summary>
    /// Conversation in which the message was sent.
    /// </summary>
    [ForeignKey(nameof(ConversationId))]
    public Conversation? Conversation { get; set; }

    /// <summary>
    /// Project in which the message was sent.
    /// </summary>
    [ForeignKey(nameof(ProjectId))]
    public Project? Project { get; set; }

    /// <summary>
    /// Message being replied to.
    /// </summary>
    [ForeignKey(nameof(ReplyToId))]
    public Message? ReplyTo { get; set; }

    /// <summary>
    /// User who pinned this message.
    /// </summary>
    [ForeignKey(nameof(PinnedByUserId))]
    public User? PinnedByUser { get; set; }

    /// <summary>
    /// Reactions attached to this message.
    /// </summary>
    public ICollection<MessageReaction> Reactions { get; set; } = new List<MessageReaction>();

    /// <summary>
    /// Temporary, heavy AI transparency payload for this message.
    /// </summary>
    public AiMessageDetails? AiDetails { get; set; }
}

/// <summary>
/// Temporary full AI transparency payload for a generated chat message.
/// Pruned after the configured retention window.
/// </summary>
[Table("AiMessageDetails")]
public class AiMessageDetails
{
    /// <summary>Message identifier and primary key for the retained AI payload.</summary>
    [Key]
    public Guid MessageId { get; set; }

    /// <summary>Full AI transparency payload stored as JSON for temporary inspection.</summary>
    [Required]
    public string FullPayloadJson { get; set; } = string.Empty;

    /// <summary>UTC timestamp when the AI payload was stored.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>Generated chat message that owns this AI transparency payload.</summary>
    [ForeignKey(nameof(MessageId))]
    public Message Message { get; set; } = null!;
}

/// <summary>
/// Emoji reaction on a chat message.
/// </summary>
[Table("MessageReactions")]
public class MessageReaction
{
    /// <summary>Primary key for an emoji reaction on a chat message.</summary>
    public Guid Id { get; set; }

    /// <summary>Message that received the emoji reaction.</summary>
    public Guid MessageId { get; set; }

    /// <summary>User who added the emoji reaction.</summary>
    public Guid UserId { get; set; }

    /// <summary>Emoji value stored for the message reaction.</summary>
    [Required]
    [MaxLength(32)]
    public string Emoji { get; set; } = string.Empty;

    /// <summary>UTC timestamp when the emoji reaction was added.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>Message that received this emoji reaction.</summary>
    [ForeignKey(nameof(MessageId))]
    public Message Message { get; set; } = null!;

    /// <summary>User who added this emoji reaction.</summary>
    [ForeignKey(nameof(UserId))]
    public User User { get; set; } = null!;
}

/// <summary>
/// Message type: direct (personal), group, or project.
/// </summary>
public enum MessageType
{
    /// <summary>
    /// Direct message in a conversation between two users.
    /// </summary>
    Direct = 0,

    /// <summary>
    /// Message in a group chat.
    /// </summary>
    Group = 1,

    /// <summary>
    /// Message in a project (project general channel).
    /// </summary>
    Project = 2
}

