import {
  Award,
  BadgeCheck,
  Briefcase,
  Bug,
  Camera,
  CheckCircle2,
  Clock,
  Code2,
  Crown,
  Eye,
  Flame,
  Gavel,
  Gem,
  GitBranch,
  Globe,
  GraduationCap,
  Handshake,
  Headset,
  Heart,
  Layers,
  Languages,
  Link2,
  ListChecks,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Network,
  PenLine,
  Puzzle,
  Rocket,
  Scale,
  ScanEye,
  Send,
  Shield,
  ShieldAlert,
  Sparkle,
  Sparkles,
  Star,
  Swords,
  Target,
  ThumbsUp,
  TrendingUp,
  Trophy,
  UserCheck,
  UserPlus,
  Users,
  Zap,
  type LucideIcon,
} from "lucide-react"

export interface BadgeStyle {
  icon: LucideIcon
}

const badgeStyleMap: Record<string, BadgeStyle> = {
  first_project: { icon: Rocket },
  five_projects: { icon: Layers },
  ten_projects: { icon: Sparkles },
  project_completed: { icon: CheckCircle2 },
  featured_project: { icon: Star },
  three_completed: { icon: Trophy },
  three_projects: { icon: Target },
  five_completed: { icon: CheckCircle2 },
  showcase_published: { icon: Eye },
  project_published: { icon: Send },
  first_team: { icon: Users },
  team_leader: { icon: Crown },
  five_teams: { icon: Handshake },
  three_teams: { icon: Network },
  ten_teams: { icon: Globe },
  project_owner: { icon: Briefcase },
  big_team: { icon: UserPlus },
  multi_role: { icon: Puzzle },
  first_follower: { icon: Heart },
  popular: { icon: TrendingUp },
  helpful: { icon: MessageSquare },
  ten_followers: { icon: Heart },
  influencer: { icon: Megaphone },
  first_review: { icon: PenLine },
  first_comment: { icon: MessageCircle },
  social_butterfly: { icon: Sparkles },
  top_rated: { icon: ThumbsUp },
  profile_complete: { icon: UserCheck },
  verified: { icon: Shield },
  early_adopter: { icon: Clock },
  avatar_set: { icon: Camera },
  skilled: { icon: Gem },
  github_connected: { icon: Link2 },
  social_presence: { icon: Globe },
  first_task: { icon: ListChecks },
  task_master: { icon: Trophy },
  streak_7: { icon: Flame },
  streak_30: { icon: Zap },
  ten_tasks: { icon: ListChecks },
  hundred_tasks: { icon: Swords },
  first_message: { icon: MessageCircle },
  chatterbox: { icon: MessageSquare },
  polyglot: { icon: Languages },
  bug_hunter: { icon: Bug },
  mentor: { icon: GraduationCap },
  open_source: { icon: Globe },
  first_contribution: { icon: GitBranch },
  code_reviewer: { icon: Code2 },
  first_moderation: { icon: Gavel },
  mod_veteran: { icon: ShieldAlert },
  guardian: { icon: Shield },
  verifier: { icon: BadgeCheck },
  issue_resolver: { icon: Scale },
  support_hero: { icon: Headset },
  curator_star: { icon: Sparkle },
  watchdog: { icon: ScanEye },
}

const defaultStyle: BadgeStyle = {
  icon: Award,
}

export function getBadgeStyle(code: string): BadgeStyle {
  return badgeStyleMap[code] ?? defaultStyle
}
